apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlpinger
  labels:
    app: urlpinger
spec:
  replicas: 3
  selector:
    matchLabels:
      app: urlpinger
  template:
    metadata:
      labels:
        app: urlpinger
    spec:
      containers:
        - name: urlpinger
          image: mamdouhel/urlpinger:v2
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
            - name: CHROME_PATH
              value: "/usr/bin/chromium"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "600Mi"
            limits:
              cpu: "1"
              memory: "1200Mi"   # âœ… integer value instead of 1.2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: urlpinger-service
  labels:
    app: urlpinger
spec:
  type: LoadBalancer
  selector:
    app: urlpinger
  ports:
    - name: http
      port: 80
      targetPort: 8080
