apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlpinger
  labels:
    app: urlpinger
spec:
  # Single replica to let one pod take advantage of the full node capacity
  replicas: 2
  selector:
    matchLabels:
      app: urlpinger
  template:
    metadata:
      labels:
        app: urlpinger
    spec:
      containers:
        - name: urlpinger
          image: mamdouhel/urlpinger:v7
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
            - name: CHROME_PATH
              value: "/usr/bin/chromium"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "3"
              memory: "6Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: urlpinger-service
  labels:
    app: urlpinger
spec:
  type: ClusterIP
  selector:
    app: urlpinger
  ports:
    - name: http
      port: 80
      targetPort: 8080
